// Runs the WaveSolver and exports per-frame amplitude data as a JavaScript
// file that the static web viewer can load directly (no server needed).
//
// Usage:  dotnet run -- [output-path]
//         output-path defaults to ../web/frames.js

using System.Text;

const int Width         = 120;
const int Height        = 120;
const int TotalSteps    = 400;
const int FrameInterval = 4;    // save every Nth step → 100 frames total

string outputPath = args.Length > 0 ? args[0] : "../web/frames.js";

// ---------------------------------------------------------------------------
// Build a speed map: double-slit barrier at x = 60
// Waves from the left diffract through the two openings and interfere —
// a visually striking physical phenomenon.
// ---------------------------------------------------------------------------
var speedMap = new double[Height, Width];
for (int y = 0; y < Height; y++)
    for (int x = 0; x < Width; x++)
        speedMap[y, x] = 1.0;

int barrierX    = Width / 2;
int slitWidth   = 5;
int slitGap     = 20;
int slitCentreY = Height / 2;
int slit1Top    = slitCentreY - slitGap / 2 - slitWidth;
int slit1Bot    = slitCentreY - slitGap / 2;
int slit2Top    = slitCentreY + slitGap / 2;
int slit2Bot    = slitCentreY + slitGap / 2 + slitWidth;

for (int y = 0; y < Height; y++)
{
    bool inSlit1 = y >= slit1Top && y < slit1Bot;
    bool inSlit2 = y >= slit2Top && y < slit2Bot;
    if (!inSlit1 && !inSlit2)
        speedMap[y, barrierX] = 0.0;   // hard wall
}

var solver = new WaveSolver(speedMap, dx: 1.0, dt: 0.4);

// Place a broad impulse to the left of the barrier — approximates a plane wave
solver.AddImpulse(cx: 20, cy: Height / 2, magnitude: 1.0, sigma: 8.0);

// ---------------------------------------------------------------------------
// Simulate and collect raw frames
// ---------------------------------------------------------------------------
var rawFrames = new List<double[]>();
double globalMax = double.Epsilon;

for (int t = 0; t < TotalSteps; t++)
{
    solver.Step();

    if (t % FrameInterval == 0)
    {
        double[,] amp = solver.Amplitude;
        var frame = new double[Width * Height];
        for (int y = 0; y < Height; y++)
            for (int x = 0; x < Width; x++)
            {
                double v = amp[y, x];
                frame[y * Width + x] = v;
                if (Math.Abs(v) > globalMax) globalMax = Math.Abs(v);
            }
        rawFrames.Add(frame);
    }
}

// ---------------------------------------------------------------------------
// Normalise each frame to signed bytes (-128..127), then base64-encode.
// 128 in the byte stream represents zero amplitude.
// ---------------------------------------------------------------------------
var encodedFrames = new List<string>(rawFrames.Count);
foreach (double[] frame in rawFrames)
{
    var bytes = new byte[frame.Length];
    for (int i = 0; i < frame.Length; i++)
    {
        double normalised = frame[i] / globalMax;          // -1 .. +1
        int quantised = (int)Math.Round(normalised * 127); // -127 .. +127
        bytes[i] = (byte)(Math.Clamp(quantised, -127, 127) + 128); // 1..255
    }
    encodedFrames.Add(Convert.ToBase64String(bytes));
}

// ---------------------------------------------------------------------------
// Write frames.js
// ---------------------------------------------------------------------------
Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);

var sb = new StringBuilder();
sb.AppendLine("// Auto-generated by Simulator — do not edit by hand.");
sb.AppendLine("// Each frame is a base64-encoded byte array (width*height bytes).");
sb.AppendLine("// Byte value 128 = zero amplitude; 255 = max positive; 1 = max negative.");
sb.AppendLine("const WAVE_DATA = {");
sb.AppendLine($"  width: {Width},");
sb.AppendLine($"  height: {Height},");
sb.AppendLine($"  frameCount: {encodedFrames.Count},");
sb.AppendLine("  frames: [");
for (int i = 0; i < encodedFrames.Count; i++)
{
    string comma = i < encodedFrames.Count - 1 ? "," : "";
    sb.AppendLine($"    \"{encodedFrames[i]}\"{comma}");
}
sb.AppendLine("  ]");
sb.AppendLine("};");

File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
Console.WriteLine($"Wrote {encodedFrames.Count} frames ({Width}x{Height}) to {outputPath}");
